/**
 * PurchaseOrderDoc — Firestore document shape for `restaurants/{restaurantId}/purchaseOrders/{poId}`.
 *
 * Represents a purchase order generated by the REPO module. The PO lifecycle flows:
 * DRAFT → APPROVED → SENT → PARTIALLY_RECEIVED → RECEIVED → CLOSED | CANCELLED.
 *
 * PO generation is client-side (ADL-004): computed from offline Firestore cache, then
 * written as a single draft document. Owner approval moves it to APPROVED status.
 * Receiving workflow updates individual line item `receivedQty` values.
 *
 * Rules:
 *  - `_schemaVersion` is always written; never stripped by serialize().
 *  - `PurchaseOrder` is the UI-facing type (no `_schemaVersion`).
 *  - Line items are embedded in the document (not a subcollection) — max ~50 items per PO.
 *  - `notes` and `deliveryDate` are omitted when absent — no nulls written to Firestore.
 */

export const PURCHASE_ORDER_SCHEMA_VERSION = 1;

/** Lifecycle status of a purchase order. */
export type PurchaseOrderStatus =
  | 'DRAFT'
  | 'APPROVED'
  | 'SENT'
  | 'PARTIALLY_RECEIVED'
  | 'RECEIVED'
  | 'CLOSED'
  | 'CANCELLED';

/** How the unit cost on this line item was determined. */
export type PriceSource = 'VENDOR_CATALOG' | 'LAST_PURCHASE' | 'MANUAL';

/** A single line item within a purchase order. Embedded in PurchaseOrderDoc. */
export interface PurchaseOrderLineItem {
  /** Firestore document ID of the RawMaterialDoc in `restaurants/{rId}/rawMaterials/{id}`. */
  rawMaterialId: string;
  /** Snapshot of the material name at time of PO creation (for display if material renamed). */
  rawMaterialName: string;
  /** Unit of measure for the ordered quantity (e.g. "kg", "bag"). */
  unit: string;
  /** Quantity to order, calculated as `parMinimum - currentStock + bufferPct`. */
  orderedQty: number;
  /** Quantity actually received during the receiving workflow. Initially 0. */
  receivedQty: number;
  /** Unit cost used for the order. Updated to actual cost on receiving. */
  unitCost: number;
  /** How `unitCost` was sourced. */
  priceSource: PriceSource;
  /** ID of the VendorCatalogItemDoc used for pricing, if applicable. Optional. */
  catalogItemRef?: string;
}

/** Firestore document shape for `restaurants/{restaurantId}/purchaseOrders/{poId}`. */
export interface PurchaseOrderDoc {
  /** Infrastructure field — drives migration logic; never shown in UI. */
  _schemaVersion: number;
  /** Current lifecycle status of the PO. */
  status: PurchaseOrderStatus;
  /** Firestore document ID of the RestaurantSupplierDoc in `restaurants/{rId}/suppliers/{id}`. */
  supplierId: string;
  /** Snapshot of the supplier name at time of PO creation. */
  supplierName: string;
  /** Embedded line items — one per raw material in the order. */
  lineItems: PurchaseOrderLineItem[];
  /** Total estimated cost at time of generation (sum of orderedQty × unitCost). */
  estimatedTotal: number;
  /** Total actual cost at time of receiving (sum of receivedQty × unitCost). */
  actualTotal: number;
  /** Buffer percentage applied to shortfall quantities (e.g. 0.1 for 10%). */
  bufferPct: number;
  /** UID of the user who generated this PO. */
  generatedByUid: string;
  /** UID of the user who approved this PO. Absent until approved. */
  approvedByUid?: string;
  /** ISO 8601 timestamp of PO creation. */
  createdAt: string;
  /** ISO 8601 timestamp of last status change. */
  updatedAt: string;
  /** Requested or confirmed delivery date. ISO 8601 date string. Optional. */
  deliveryDate?: string;
  /** Free-form notes for the supplier. Optional. */
  notes?: string;
}

/**
 * UI-facing type — `_schemaVersion` stripped.
 * Components and signals use this type exclusively.
 */
export type PurchaseOrder = Omit<PurchaseOrderDoc, '_schemaVersion'>;

/** Canonical defaults for a new draft PO. */
export const PURCHASE_ORDER_DEFAULTS: PurchaseOrder = {
  status: 'DRAFT',
  supplierId: '',
  supplierName: '',
  lineItems: [],
  estimatedTotal: 0,
  actualTotal: 0,
  bufferPct: 0.1,
  generatedByUid: '',
  createdAt: '',
  updatedAt: '',
};

/**
 * Normalise a raw Firestore snapshot into a fully-typed `PurchaseOrder`.
 */
export function deserializePurchaseOrder(raw: unknown): PurchaseOrder {
  const data = (raw ?? {}) as Partial<PurchaseOrderDoc>;

  // --- Migration gate (expand as schema evolves) ---

  return {
    status: data.status ?? PURCHASE_ORDER_DEFAULTS.status,
    supplierId: data.supplierId ?? PURCHASE_ORDER_DEFAULTS.supplierId,
    supplierName: data.supplierName ?? PURCHASE_ORDER_DEFAULTS.supplierName,
    lineItems: data.lineItems ?? PURCHASE_ORDER_DEFAULTS.lineItems,
    estimatedTotal:
      data.estimatedTotal ?? PURCHASE_ORDER_DEFAULTS.estimatedTotal,
    actualTotal: data.actualTotal ?? PURCHASE_ORDER_DEFAULTS.actualTotal,
    bufferPct: data.bufferPct ?? PURCHASE_ORDER_DEFAULTS.bufferPct,
    generatedByUid:
      data.generatedByUid ?? PURCHASE_ORDER_DEFAULTS.generatedByUid,
    createdAt: data.createdAt ?? PURCHASE_ORDER_DEFAULTS.createdAt,
    updatedAt: data.updatedAt ?? PURCHASE_ORDER_DEFAULTS.updatedAt,
    ...(data.approvedByUid ? { approvedByUid: data.approvedByUid } : {}),
    ...(data.deliveryDate ? { deliveryDate: data.deliveryDate } : {}),
    ...(data.notes ? { notes: data.notes } : {}),
  };
}

/**
 * Produce a null-free Firestore-safe `PurchaseOrderDoc` from the UI-facing `PurchaseOrder`.
 */
export function serializePurchaseOrder(po: PurchaseOrder): PurchaseOrderDoc {
  return {
    _schemaVersion: PURCHASE_ORDER_SCHEMA_VERSION,
    status: po.status,
    supplierId: po.supplierId,
    supplierName: po.supplierName,
    lineItems: po.lineItems,
    estimatedTotal: po.estimatedTotal,
    actualTotal: po.actualTotal,
    bufferPct: po.bufferPct,
    generatedByUid: po.generatedByUid,
    createdAt: po.createdAt,
    updatedAt: po.updatedAt,
    ...(po.approvedByUid ? { approvedByUid: po.approvedByUid } : {}),
    ...(po.deliveryDate ? { deliveryDate: po.deliveryDate } : {}),
    ...(po.notes ? { notes: po.notes } : {}),
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Returns the sum of `orderedQty × unitCost` across all line items. */
export function computeEstimatedTotal(
  lineItems: PurchaseOrderLineItem[],
): number {
  return lineItems.reduce(
    (sum, item) => sum + item.orderedQty * item.unitCost,
    0,
  );
}

/** Returns the sum of `receivedQty × unitCost` across all line items. */
export function computeActualTotal(lineItems: PurchaseOrderLineItem[]): number {
  return lineItems.reduce(
    (sum, item) => sum + item.receivedQty * item.unitCost,
    0,
  );
}
