/**
 * write-env.mjs
 *
 * Injects Firebase production credentials from environment variables into
 * environments/environment.prod.ts at CI build time.
 *
 * Required environment variables (set as GitHub Secrets):
 *   FIREBASE_API_KEY
 *   FIREBASE_AUTH_DOMAIN
 *   FIREBASE_PROJECT_ID
 *   FIREBASE_STORAGE_BUCKET
 *   FIREBASE_MESSAGING_SENDER_ID
 *   FIREBASE_APP_ID
 *
 * Run: node scripts/write-env.mjs
 */

import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const required = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];

const missing = required.filter((key) => !process.env[key]);
if (missing.length > 0) {
  console.error(
    `❌ Missing required environment variables:\n  ${missing.join("\n  ")}`,
  );
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/write-env.mjs — DO NOT EDIT MANUALLY
export const environment = {
  production: true,
  useEmulators: false,
  firebase: {
    apiKey: "${process.env.FIREBASE_API_KEY}",
    authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
    projectId: "${process.env.FIREBASE_PROJECT_ID}",
    storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${process.env.FIREBASE_APP_ID}"
  }
};
`;

const outputPath = resolve(__dirname, "../environments/environment.prod.ts");
writeFileSync(outputPath, content, "utf8");
console.log(`✅ environment.prod.ts written to ${outputPath}`);
